version: 2.1
executors:
  lint-env:
    docker:
      - image: mere/dev
  build-env:
    machine:
      image: ubuntu-2004:202107-02
jobs:
  lint:
    executor: lint-env
    steps:
      - run:
          name: Install tools and upgrade
          command: pacman -Sy --noconfirm git openssh-client shellcheck
      - checkout
      - run:
          name: Shellcheck
          command: |
            find packages -name PKGBUILD -exec shellcheck '{}' +
            find packages -name PKGTEST -exec shellcheck '{}' +
            find buildpkg.sh ci-scripts dev-scripts misc-util -type f -exec shellcheck '{}' +
  build:
    executor: build-env
    steps:
      - checkout
      - run:
          name: Setup Build
          command: ./ci-scripts/ci-setup.sh
      - run:
          name: Build package
          command: ./ci-scripts/ci-build.sh
          no_output_timeout: 20m
      - run:
          name: Test package
          command: ./ci-scripts/ci-test.sh
      - run:
          name: Upload package
          command: ./ci-scripts/ci-upload.sh
workflows:
  version: 2
  workflow:
    jobs:
      - lint:
        filters:
          branches:
            ignore: gh-pages
      - build:
          requires:
            - lint
