version: 2.1
executors:
  dev-image:
    docker:
      - image: mere/dev
  build-machine:
    resource_class: large
    machine:
      image: ubuntu-2204:2022.10.2
jobs:
  lint:
    executor: dev-image
    steps:
      - run:
          name: Install tools and upgrade
          command: pacman -Syu --noconfirm git openssh-client shellcheck
      - checkout
      - run:
          name: Shellcheck
          command: |
            find packages -name PKGBUILD -exec shellcheck '{}' +
            find packages -name PKGTEST -exec shellcheck '{}' +
            find ci-scripts -type f -exec shellcheck '{}' +
  build-parallel:
    executor: build-machine
    steps:
      - checkout
      - run:
          name: Setup Build
          command: ./ci-scripts/ci-setup.sh
      - run:
          name: Build package
          command: ./ci-scripts/ci-build.sh
          no_output_timeout: 20m
      - run:
          name: Test package
          command: ./ci-scripts/ci-test.sh
      - run:
          name: Upload package
          command: ./ci-scripts/ci-upload.sh
          when:
            condition:
              equal: [ main, << pipeline.git.branch >> ]
      - run:
          name: Cleanup
          command: sudo tailscale logout
          when: always
    parallelism: 6
  build:
    executor: build-machine
    steps:
      - checkout
      - run:
          name: Setup Build
          command: ./ci-scripts/ci-setup.sh
      - run:
          name: Build package
          command: ./ci-scripts/ci-build.sh
          no_output_timeout: 20m
      - run:
          name: Test package
          command: ./ci-scripts/ci-test.sh

workflows:
  version: 2
  parallel:
    when:
      or:
        - matches:
            pattern: "^.*-parallel$"
            value: << pipeline.git.branch >>
        - equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - lint
      - build-parallel
  single:
    when:
      and:
        - not:
            matches:
              pattern: "^.*-parallel$"
              value: << pipeline.git.branch >>
        - not:
            equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - lint
      - build
