version: 2.1
executors:
  amd64-build-machine:
    resource_class: large
    machine:
      image: ubuntu-2204:2022.10.2
  arm64-build-machine:
    resource_class: arm.large
    machine:
      image: ubuntu-2204:2022.10.2
jobs:
  build-amd64:
    executor: amd64-build-machine
    steps:
      - checkout
      - run:
          name: Setup Build
          command: ./ci-scripts/ci-setup.sh
      - run:
          name: Build package
          command: ./ci-scripts/ci-build.sh
          no_output_timeout: 20m
      - run:
          name: Test package
          command: ./ci-scripts/ci-test.sh
  build-arm64:
    executor: arm64-build-machine
    steps:
      - checkout
      - run:
          name: Setup Build
          command: ./ci-scripts/ci-setup.sh
      - run:
          name: Build package
          command: ./ci-scripts/ci-build.sh
          no_output_timeout: 20m
      - run:
          name: Test package
          command: ./ci-scripts/ci-test.sh
  build-main-amd64:
    executor: amd64-build-machine
    steps:
      - checkout
      - run:
          name: Setup Build
          command: ./ci-scripts/ci-setup.sh
      - run:
          name: Build package
          command: ./ci-scripts/ci-build.sh
          no_output_timeout: 20m
      - run:
          name: Test package
          command: ./ci-scripts/ci-test.sh
      - run:
          name: Upload package
          command: ./ci-scripts/ci-upload.sh
  build-main-arm64:
    executor: arm64-build-machine
    steps:
      - checkout
      - run:
          name: Setup Build
          command: ./ci-scripts/ci-setup.sh
      - run:
          name: Build package
          command: ./ci-scripts/ci-build.sh
          no_output_timeout: 20m
      - run:
          name: Test package
          command: ./ci-scripts/ci-test.sh
      - run:
          name: Upload package
          command: ./ci-scripts/ci-upload.sh
workflows:
  version: 2
  single:
    when:
      not:
        equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - build-amd64
      - build-arm64
  main:
    when:
      equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - build-main-amd64
      - build-main-arm64
