version: 2.1
executors:
  dev-image:
    docker:
      - image: mere/dev
  build-machine:
    resource_class: large
    machine:
      image: ubuntu-2204:2022.10.2
jobs:
  lint:
    executor: dev-image
    steps:
      - run:
          name: Install tools and upgrade
          command: pacman -Syu --noconfirm git openssh-client shellcheck
      - checkout
      - run:
          name: Shellcheck
          command: |
            find packages -name PKGBUILD -exec shellcheck '{}' +
            find packages -name PKGTEST -exec shellcheck '{}' +
            find buildpkg.sh ci-scripts dev-scripts misc-util -type f -exec shellcheck '{}' +
  build-parallel:
    executor: build-machine
    steps:
      - checkout
      - run:
          name: Setup Build
          command: ./ci-scripts/ci-setup.sh
      - run:
          name: Build package
          command: ./ci-scripts/ci-build.sh
          no_output_timeout: 20m
      - run:
          name: Test package
          command: ./ci-scripts/ci-test.sh
      - run:
          name: Cleanup
          command: sudo tailscale logout
          when: always
      - store_artifacts:
          path: /tmp/mere
    parallelism: 6
  build:
    executor: build-machine
    steps:
      - checkout
      - run:
          name: Setup Build
          command: ./ci-scripts/ci-setup.sh
      - run:
          name: Build package
          command: ./ci-scripts/ci-build.sh
          no_output_timeout: 20m
      - run:
          name: Test package
          command: ./ci-scripts/ci-test.sh
      - store_artifacts:
          path: /tmp/mere
  upload:
    executor: build-machine
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache:
          key: testing-repo-v4-
      - run:
          name: Upload package
          command: ./ci-scripts/ci-upload.sh
      - save_cache:
          key: testing-repo-v4-{{ checksum "pkgs/testing/testing.db.tar.gz" }}
          paths: pkgs/testing

workflows:
  version: 2
  parallel:
    when:
      matches:
        pattern: "^.*-parallel$"
        value: << pipeline.git.branch >>
    jobs:
      - lint
      - build-parallel
  single:
    when:
      and:
        - not:
            matches:
              pattern: "^.*-parallel$"
              value: << pipeline.git.branch >>
        - not:
            equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - lint
      - build
  upload:
    when:
      equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - upload
