version: 2
jobs:
  lint:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          name: Shellcheck PKGBUILDs
          command: find packages -name PKGBUILD -exec shellcheck '{}' +
      - run:
          name: Shellcheck scripts
          command: find scripts -type f -exec shellcheck '{}' +
  build:
    docker:
      - image: mere/build-essential
    steps:
      - checkout
      - run:
          name: Build package
          command: ./scripts/ci-build.sh
workflows:
  version: 2
  workflow:
    jobs:
      - lint
      - build